name 'puppetlabs-passenger'
version '0.0.99'

author 'puppetlabs'
license 'Apache 2.0'
project_page 'https://github.com/puppetlabs/puppetlabs-passenger'
source 'git://github.com/puppetlabs/puppetlabs-passenger.git'
summary 'Puppet module for Passenger'
description 'Module for Passenger configuration. This is a spoof class since the original will destroy the Ubuntu installation.
The original passenger module needs to be upgraded first.'
