fixtures:
  symlinks:
    puppet: "#{source_dir}"
    ruby: "#{source_dir}/../ruby"
    passenger: "#{source_dir}/../passenger"
    apache: "#{source_dir}/../apache"
    stdlib: "#{source_dir}/../stdlib"
    firewall: "#{source_dir}/../firewall"
    concat: "#{source_dir}/../concat"
