require 'puppetlabs_spec_helper/rake_tasks'

desc "Run spec tests and output html log"
RSpec::Core::RakeTask.new(:spec_html_standalone) do |t|
  t.rspec_opts = ['-O spec/spec.opts']
  t.pattern = 'spec/{classes,defines,unit,functions,hosts}/**/*_spec.rb'
end

desc "Run spec tests in a clean fixtures directory and output as html log"
task :spec_html do
  Rake::Task[:spec_prep].invoke
  Rake::Task[:spec_html_stanalone].invoke
  Rake::Task[:spec_clean].invoke
end
